# X-AnyLabeling 🌟, GPL-3.0-only license

blank_issues_enabled: true
contact_links:
  - name: 📃 Docs
    url: https://xanylabeling.com/docs/x-anylabeling/get_started
    about: Full X-AnyLabeling Documentation
