type: rio_detr
name: rio_detr_s_dota_1_ss-r20260808
provider: USTC
display_name: RT-DETRv2-OBB-S (DOTA-v1.0)
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v3.0.0/rtdetrv2_obb_hgnetv2_s_dota_1_ss.onnx
conf_threshold: 0.40
classes:
  - plane
  - baseball-diamond
  - bridge
  - ground-track-field
  - small-vehicle
  - large-vehicle
  - ship
  - tennis-court
  - basketball-court
  - storage-tank
  - soccer-ball-field
  - roundabout
  - harbor
  - swimming-pool
  - helicopter
