type: yolo26_obb_track
name: yolo26s_obb_tracktrack-r20260620
provider: Ultralytics
display_name: YOLO26s-OBB-TrackTrack (DOTA-v1.0)
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v3.0.0/yolo26s-obb.onnx
conf_threshold: 0.25
iou_threshold: 0.5
max_det: 300
tracker:
  tracker_type: tracktrack
  track_high_thresh: 0.6
  track_low_thresh: 0.25
  new_track_thresh: 0.7
  track_buffer: 30
  match_thresh: 0.7
  lost_match_thr: 0.0
  iou_weight: 0.5
  conf_weight: 0.1
  angle_weight: 0.05
  penalty_p: 0.2
  reduce_step: 0.05
  tai_thr: 0.55
  min_track_len: 3
  gmc_method: sparseOptFlow
classes:
  - plane
  - ship
  - storage tank
  - baseball diamond
  - tennis court
  - basketball court
  - ground track field
  - harbor
  - bridge
  - large vehicle
  - small vehicle
  - helicopter
  - roundabout
  - soccer ball field
  - swimming pool
