type: yolo26_pose_track
name: yolo26s_pose_tracktrack-r20260620
provider: Ultralytics
display_name: YOLO26s-Pose-TrackTrack
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v3.0.0/yolo26s-pose.onnx
conf_threshold: 0.5
iou_threshold: 0.6
kpt_threshold: 0.25
max_det: 300
has_visible: true
show_boxes: True
tracker:
  tracker_type: tracktrack
  track_high_thresh: 0.6
  track_low_thresh: 0.25
  new_track_thresh: 0.7
  track_buffer: 30
  match_thresh: 0.7
  lost_match_thr: 0.0
  iou_weight: 0.5
  conf_weight: 0.1
  angle_weight: 0.05
  penalty_p: 0.2
  reduce_step: 0.05
  tai_thr: 0.55
  min_track_len: 3
  gmc_method: sparseOptFlow
classes:
  person:
    - nose
    - left_eye
    - right_eye
    - left_ear
    - right_ear
    - left_shoulder
    - right_shoulder
    - left_elbow
    - right_elbow
    - left_wrist
    - right_wrist
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
