type: yolov8_obb_track
name: yolov8n_obb_botsort-r20240816
provider: Ultralytics
display_name: YOLOv8n-Obb-BoT-SORT
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/yolov8n_obb_car_bus.onnx
iou_threshold: 0.5
conf_threshold: 0.1
tracker:
  # Base settings
  tracker_type: botsort # tracker type, ['botsort', 'bytetrack']
  track_high_thresh: 0.5 # threshold for the first association
  track_low_thresh: 0.1 # threshold for the second association
  new_track_thresh: 0.6 # threshold for init new track if the detection does not match any tracks
  track_buffer: 30 # buffer to calculate the time when to remove tracks
  match_thresh: 0.8 # threshold for matching tracks
  fuse_score: True
  # BoT-SORT settings
  gmc_method: sparseOptFlow # method of global motion compensation
  # ReID model related thresh (not supported yet)
  proximity_thresh: 0.5
  appearance_thresh: 0.25
  with_reid: False
classes:
  - car
  - bus